version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./config:/var/www/html/config
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV:-production}
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE:-sistema_captacion}
      - DB_USERNAME=${DB_USERNAME:-captacion_user}
      - DB_PASSWORD=${DB_PASSWORD:-captacion_password}
      - UPLOAD_MAX_FILESIZE=20M
      - POST_MAX_SIZE=20M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: ${DB_USERNAME:-captacion_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-captacion_password}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-captacion_password}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE:-sistema_captacion}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME:-captacion_user}
      PMA_PASSWORD: ${DB_PASSWORD:-captacion_password}
      PMA_ARBITRARY: 1
    depends_on:
      - db

volumes:
  db_data:
